development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mysite_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mysite_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mysite_production
